### ISSUE TITLE
`require-shim` having trouble to build with `esbuild` on AWS Lambda serverless

### ISSUE THREAD

**Issue by yumin-chen** [brillout/require-shim#1]
Hi,

I'm tying to build and deploy the example Vike (previously `vite-plugin-ssr`, now `vike`) React app to AWS Lambda using Serverless, but I've got below errors:

Log trace from AWS Lambda serverless:
```
Error: [@brillout/require-shim] You stumbled upon a bug. Go to https://github.com/brillout/require-shim/issues/new and copy-paste this error. A maintainer will fix the bug.
    at assert3 (/node_modules/@brillout/require-shim/dist/utils.cjs:33:11)
    at testShim (/node_modules/@brillout/require-shim/dist/index.cjs:130:21)
    at installRequireShim2 (/node_modules/@brillout/require-shim/dist/index.cjs:38:5)
    at onLoad (/node_modules/vike/dist/esm/node/runtime/onLoad.js:8:5)
    at node_modules/vike/dist/esm/node/runtime/utils.js (/node_modules/vike/dist/esm/node/runtime/utils.js:4:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at node_modules/vike/dist/esm/node/runtime/html/renderHtml.js (/node_modules/vike/dist/esm/node/runtime/html/renderHtml.js:6:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js (/node_modules/vike/dist/esm/node/runtime/renderPage/renderPageAlreadyRouted.js:7:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at node_modules/vike/dist/esm/node/runtime/renderPage.js (/node_modules/vike/dist/esm/node/runtime/renderPage.js:3:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at node_modules/vike/dist/esm/node/runtime/index-common.js (/node_modules/vike/dist/esm/node/runtime/index-common.js:1:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at node_modules/vike/dist/esm/node/runtime/index.js (/node_modules/vike/dist/esm/node/runtime/index.js:1:1)
    at __init (file:///var/task/server/index.mjs:16:56)
    at <anonymous> (/server/index.ts:16:1)
```

**Comment by brillout** [comment]
Let me have a look.

**Comment by brillout** [comment]
Insert the following before line `130` at `/node_modules/@brillout/require-shim/dist/index.cjs`:

```diff
    if ((0, utils_cjs_1.isVitest)())
        return;
+   console.log("!('_is_brillout_require_shim' in require)", !('_is_brillout_require_shim' in require));
+   console.log("!('_is_brillout_require_shim' in globalThis.require)", !('_is_brillout_require_shim' in globalThis.require));
+   console.log("require !== globalThis.require", require !== globalThis.require);
+   console.log("require", require);
+   console.log("globalThis.require", globalThis.require);
    (0, utils_cjs_1.assert)(require !== globalThis.require);
    (0, utils_cjs_1.assert)(!('_is_brillout_require_shim' in require));
```

And report back the log results.

**Comment by yumin-chen** [comment]
Is there a way for you to disable the `testShim`?

We're adding some custom JS banner that overrides `globalThis.require` using ESBuild as part of the build process, which seems to be in conflict with `require-shim`, as you're testing the `globalThis.require`.




```yml
  esbuild:
    banner:
      js: 'await(async()=>{let{dirname:e}=await import("path"),{fileURLToPath:i}=await import("url");if(typeof globalThis.__filename>"u"&&(globalThis.__filename=i(import.meta.url)),typeof globalThis.__dirname>"u"&&(globalThis.__dirname=e(globalThis.__filename)),typeof globalThis.require>"u"){let{default:a}=await import("module");globalThis.require=a.createRequire(import.meta.url)}})();'
```

```javascript
await (async () => {
  let {
    dirname: e
  } = await import("path"), {
    fileURLToPath: i
  } = await import("url");
  if (typeof globalThis.__filename > "u" && (globalThis.__filename = i(
      import.meta.url)), typeof globalThis.__dirname > "u" && (globalThis.__dirname = e(globalThis.__filename)), typeof globalThis.require > "u") {
    let {
      default: a
    } = await import("module");
    globalThis.require = a.createRequire(
      import.meta.url)
  }
})();
```
